[package]
name = "wayland-client"
version = "0.24.0-pre"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
edition = "2018"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to the standard C implementation of the wayland protocol, client side."
build = "build.rs"

[badges]
travis-ci = { repository = "Smithay/wayland-rs" }

[dependencies]
wayland-commons = { version = "0.24.0-pre", path = "../wayland-commons" }
wayland-sys = { version = "0.24.0-pre", path = "../wayland-sys" }
nix = "0.15"
downcast-rs = "1.0"
bitflags = "1.0"
libc = "0.2"
scoped-tls = { version = "1.0", optional = true }

[build-dependencies]
wayland-scanner = { version = "0.24.0-pre", path = "../wayland-scanner" }

[dev-dependencies]
byteorder = "1.0"
tempfile = ">=2.0, <4.0"

[features]
use_system_lib = [ "wayland-sys/client", "scoped-tls"]
dlopen = ["wayland-sys/dlopen", "use_system_lib"]
