[package]
name = "wayland-server"
version = "0.24.0-pre"
documentation = "https://smithay.github.io/wayland-rs/wayland_server/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "server", "compositor"]
description = "Bindings to the standard C implementation of the wayland protocol, server side."
build = "build.rs"
edition = "2018"

[badges]
travis-ci = { repository = "Smithay/wayland-rs" }

[dependencies]
wayland-commons = { version = "0.24.0-pre", path = "../wayland-commons" }
wayland-sys = { version = "0.24.0-pre", path = "../wayland-sys" }
bitflags = "1.0"
downcast-rs = "1.0"
libc = "0.2"
nix = "0.15"
lazy_static = { version = "1.0", optional = true}
parking_lot = "0.9"

[build-dependencies]
wayland-scanner = { version = "0.24.0-pre", path = "../wayland-scanner" }

[features]
use_system_lib = [ "wayland-sys/server", "lazy_static" ]
dlopen = [ "wayland-sys/dlopen", "use_system_lib" ]
